# 主逻辑
[main]
9

# bndmat.txt
# note: do NOT use when QM calculation used difuse function
[mayer]
1
y

# bndmat.txt
# note: this is useless
[wiberg]
3
y

# bndmat.txt
# note: this is useless
[mulliken]
4
y

# bndmat.txt
# note: use this when QM calculation used difuse function
[fuzzy]
7
y

# note: do NOT use in system with heavy atoms
# note: This is expensive
[Laplacian]
8
y

[writegjf]
0
1000
13
9

# 退出
[quit]
0
q
