# 主逻辑
[main]
7

[hirshfeld]
1
1
y

[mulliken]
5
1
y
0

[aim]
6
${pop:-}
y

[adch]
11
1
y

[RESP]
18
1
y
0

[RESP-eqvcons]
18
5
1
${eqvcons:-eqvcons.txt}
1
y
0

[RESP-conf]
18
-1
${conformers:-conformers.txt}
5
1
${eqvcons:-eqvcons.txt}
1
0

# 退出
[quit]
0
q
