# 主逻辑
[main]
1000
2
-1
4

[autoplot]
100
1    # Color-filled map
${grid:-200,200}
4    # Define by three atoms
${plane}
4    # ATOM
5
8    # BOND
14
0
-6   # plane.txt
-5
4

[drawplot]
100
1    # Color-filled map
${grid:-200,200}
4    # Define by three atoms
${plane}
4    # ATOM
5
8    # BOND
14
0

[quit]
-10
q