# 主逻辑
[main]
100
22
0
${clean:-2} # 1: remove pi 2: remove sigma
0

[lol-pi]
4
10
1    # Color-filled map
${grid:-200,200}
4    # Define by three atoms
${plane}
4    # ATOM
5
8    # BOND
14
0

[lol-pi-wait]
4
10
1    # Color-filled map
${grid:-200,200}
4    # Define by three atoms
${plane}
4    # ATOM
5
8    # BOND
14
0





