[main]
300
4

[mod_volt]
2
${volt}
0
5           # 显示化学键
14          # 用棕色
2           # 修改图像类型
2           # 填色图+等值线
7           # 修改坐标轴的刻度间隔
1.5,1.5,0.002
-3          #其它作图设置
8           # 修改原子标签大小
70
0       
1

[direct]
0
5           # 显示化学键
14          # 用棕色
2           # 修改图像类型
2           # 填色图+等值线
7           # 修改坐标轴的刻度间隔
1.5,1.5,0.002
-3          #其它作图设置
8           # 修改原子标签大小
70
0       
1


