[main]
12

[espext]
3
0.15
0
5
mol.pdb
6
2
-1
-1
12

# surfanalysis.pdb
[alieext]
1               # Select the way to define surface
1               #  Isosurface of electron density
${iso:-0.0005}          
2               # Select mapped function
2               # Average local ionization energy (ALIE)
0
2
-1
-1
12

[leaeext]
1               # Select the way to define surface
1               #  Isosurface of electron density
${iso:-0.004}          
2               # Select mapped function
-4               # Local electron attachment energy (LEAE)
0
2
-1
-1
12

[quit]
-1
q