#ifndef INPUT_H
#define INPUT_H
#include "grep_dsl.h"
#include <string>
#include <map>
#include <tuple>
#include <vector>

enum class TaskKind {
    Workflow,
    WfnRebase,
    Collect,
    Builtin,
    Citation,
    CitationOutput
};

// Single module task information
struct ModuleTask {
    TaskKind kind = TaskKind::Workflow;
    std::string moduleName;
    std::map<std::string, std::string> params;
    std::vector<std::pair<std::string, std::map<std::string, std::string>>> postProcessSteps;
    std::vector<std::string> preRawCommands;  // Commands from %preraw block (inserted before [main])
    std::vector<std::string> rawCommands;  // Commands from %raw block (literal Multiwfn input sequence)
    std::vector<GrepRule> grepRules;  // Structured text-extraction rules from %grep blocks
    std::vector<std::string> grepErrors;  // Deferred syntax errors reported by the %grep parser
    std::vector<std::string> commands;  // Commands from %command block
    bool useWait = false;  // Whether to use wait mode (interactive mode)
    std::string wfnFile;  // Reserved: optional per-task wavefunction file (currently unused)
    int blockIndex = 0;  // Unique index for blocks with same module name

    // Special directive: wfn_rebase=xxx
    // A WfnRebase task will NOT invoke Multiwfn.
    // Instead, it updates the current file provided to subsequent Multiwfn tasks.
    std::string wfnRebaseFile;

    // Special directive: collect(path);
    // A Collect task will NOT invoke Multiwfn or shell commands.
    // Instead, it flushes all files newly created by preceding tasks into collectDir.
    std::string collectDir;

    // Built-in high-level DSL block, e.g. bane.cube.make / bane.line.profile / bane.plane.map.
    // Builtins are generated by C++ instead of external .conf templates, so their syntax can
    // describe chemistry concepts directly while keeping legacy [module] blocks intact.
    std::string builtinName;   // e.g. "cube.make", "line.profile", "plane.map"
    std::string builtinId;     // user-facing artifact/logical name after the command name
    std::vector<std::string> builtinBody;  // repeated list-like entries, currently op/operator/combine

    // Citation metadata blocks. Citation fields and output options are stored in params.
    std::string citationId;          // bane.cite <id>
    std::string citationOutputName;  // bane.citations.write <name>
    std::string origin;              // e.g. input:workflow.bw:12

    bool isWorkflow() const noexcept { return kind == TaskKind::Workflow; }
    bool isWfnRebase() const noexcept { return kind == TaskKind::WfnRebase; }
    bool isCollect() const noexcept { return kind == TaskKind::Collect; }
    bool isBuiltin() const noexcept { return kind == TaskKind::Builtin; }
    bool isCitation() const noexcept { return kind == TaskKind::Citation; }
    bool isCitationOutput() const noexcept { return kind == TaskKind::CitationOutput; }
};

// Execution options
struct ExecutionOptions {
    bool dryrun = false;
    bool screen = false;
    bool nogui = false;
    bool noColor = false;
    std::string citationsOutput;
    bool citationsOutputSpecified = false;
    std::vector<std::string> extargs;  // Extra arguments to pass to Multiwfn
    std::map<std::string, std::vector<std::string>> customVars;  // Custom variables from command line (supports arrays)

};

// Parsed input file with named fields. Prefer this over tuple-returning helpers
// when adding new input header fields or passing parsed input through layers.
struct ParsedInputFile {
    std::vector<ModuleTask> tasks;
    std::string wfnFile;
    int cores = -1;
    std::map<std::string, std::vector<std::string>> customVars;
    bool dryrun = false;
    bool nogui = false;
    std::string citationsOutput;
    bool citationsOutputSpecified = false;
    bool loaded = false;
};

// Input parser class
class InputParser {
public:
    // Parse inp file, return all module tasks
    static std::vector<ModuleTask> parseInpFile(const std::string& inpFile);
    // Parse inp file, return all module tasks and optional wfn file
    static std::pair<std::vector<ModuleTask>, std::string> parseInpFileWithWfn(const std::string& inpFile);
    // Parse inp file, return all module tasks, optional wfn file, and core count
    static std::tuple<std::vector<ModuleTask>, std::string, int> parseInpFileWithWfnAndCores(const std::string& inpFile);
    // Parse inp file, returning a named result object. This is the canonical API.
    static ParsedInputFile parseInpFileDetailed(const std::string& inpFile);
    // Parse inp file, return all module tasks, optional wfn file, core count,
    // custom variables, and whether header dryrun/nogui modes are enabled.
    // Kept for backward compatibility with existing callers/tests.
    static std::tuple<std::vector<ModuleTask>, std::string, int,
                      std::map<std::string, std::vector<std::string>>, bool, bool>
    parseInpFileWithWfnAndCoresAndVars(const std::string& inpFile);
    // Resolve interactive custom variables, including special var* / len(var) prompts.
    static void resolveInteractiveCustomVars(std::map<std::string, std::vector<std::string>>& customVars);
    // Apply placeholder replacement to all tasks using wavefunction filename and custom variables
    static void applyPlaceholderReplacement(std::vector<ModuleTask>& tasks, const std::string& wfnFile, const std::map<std::string, std::vector<std::string>>& customVars = std::map<std::string, std::vector<std::string>>());
    
private:
    // Replace input file placeholders ($input and ${input}) with wavefunction filename without extension
    // Also support custom variables from command line or file header
    // customVars: map from variable name to vector of values (for arrays, use first element for replacement)
    static std::string replaceInputPlaceholders(const std::string& text, const std::string& wfnFile, const std::map<std::string, std::vector<std::string>>& customVars = std::map<std::string, std::vector<std::string>>());
};

#endif // INPUT_H
